services:
  react-app:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports: 
      - "3000:3000"
    volumes:
      - /home/node/app/node_modules
      - .:/home/node/app
  react-app-test:
    build:
      context: .
      dockerfile: Dockerfile.test
    volumes:
      - /home/node/app/node_modules
      - .:/home/node/app
